Fix unknown path format error in wsl2
serverless/serverless-python-requirements pull request #667
Opened 2022-01-25 19:55 UTC by snicmakino

This change solves the problem [#470](https://github.com/serverless/serverless-python-requirements/issues/371) that is occurring in wsl2.
In order to make wsl2 work as well as linux, the wsl decision was changed so that it only applies to wsl1.

2022-01-26 08:05 UTC, pgrzesik requested changes
Hello @snicmakino - thanks a lot for this, could you please address the formatting issues before merging?

2022-01-26 09:14 UTC, snicmakino commented
Hello @pgrzesik

> Hello @snicmakino - thanks a lot for this, could you please address the formatting issues before merging?

Thank you for pointing that out.
I fixed it and I confirmed that `prettier-check:updated` is fine.

2022-01-26 10:12 UTC, pgrzesik approved these changes
Thank you @snicmakino 👍

2022-01-26 10:13 UTC, merged

2022-01-28 13:39 UTC, EnzoMolion commented
Hi guys!

First, thanks for the amazing tool that is Serverless, it is much appreciated

Do you, by any chance, have an idea of when this fix will be shipped in a release?

Thanks

2022-01-28 13:48 UTC, pgrzesik commented
Hey @EnzoMolion - I was planning to do a release either today or early next week.

2022-01-28 14:53 UTC, EnzoMolion commented
Ok, thanks a lot

2022-01-31 09:51 UTC, EnzoMolion commented
Tested it today, it works like a charm, thanks @snicmakino and @pgrzesik